// operations
var a=20;
var b=10;
var sum=a+b;
var sub=a-b;
var mul=a*b;
var div=a/b;
var mod=a%b;
var exp=a**b;
console.log("Sum: "+sum);
console.log("Sub: "+sub);
console.log("Mul: "+mul);
console.log("Div: "+div);
console.log("Mod: "+mod);
console.log("Exp: "+exp);